version: '2'

services:
    books-nginx:
        image: nginx:latest
        container_name: books-nginx
        ports:
        - "8080:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        links:
            - db
            - books-php
    books-php:
        build: ./docker/php
        container_name: books-php
        volumes:
            - ./:/var/www/project
        networks:
            - code-network
        links:
            - db
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: symfony
        networks:
            - code-network

volumes:
    persistent:

networks:
    code-network:
        driver: bridge